local total = 0
local locale_eng = os.setlocale(nil,all)
--local locale_rus = os.setlocale('Russian_Russia.65001',"ctype")
--local locale_rus = os.setlocale('en_US',all)
--local locale_rus_num = os.setlocale('en_US.utf8',numeric)
local untranslated = {}
local translations = {
{'3d_armor:boots_bronze','Бронзовые сапоги'},
{'3d_armor:boots_diamond','Алмазные сапоги'},
{'3d_armor:boots_mithril','Митриловые сапоги'},
{'3d_armor:boots_steel','Стальные сапоги'},
{'3d_armor:boots_wood','Деревянные сапоги'},
{'3d_armor:chestplate_bronze','Бронзовый нагрудник'},
{'3d_armor:chestplate_diamond','Алмазный нагрудник'},
{'3d_armor:chestplate_mithril','Митриловый нагрудник'},
{'3d_armor:chestplate_steel','Стальной нагрудник'},
{'3d_armor:chestplate_wood','Деревянный нагрудник'},
{'3d_armor:helmet_bronze','Бронзовый шлем'},
{'3d_armor:helmet_diamond','Алмазный шлем'},
{'3d_armor:helmet_mithril','Митриловый шлем'},
{'3d_armor:helmet_steel','Стальной шлем'},
{'3d_armor:helmet_wood','Деревянный шлем'},
{'3d_armor:leggings_bronze','Бронзовые поножи'},
{'3d_armor:leggings_diamond','Алмазные поножи'},
{'3d_armor:leggings_mithril','Митриловые поножи'},
{'3d_armor:leggings_steel','Стальные поножи'},
{'3d_armor:leggings_wood','Деревянные поножи'},
{'air','Воздух (Ах ты... Хакер, блин!)'},
{'bucket:bucket_empty','Ведро (пустое)'},
{'bucket:bucket_lava','Ведро лавы'},
{'bucket:bucket_water','Ведро воды'},
{'cake:cake','Торт'},
{'cake:cake_1','Торт [остался 1 кусочек]'},
{'cake:cake_2','Торт [осталось 2 кусочка]'},
{'cake:cake_3','Торт [осталось 3 кусочка]'},
{'cake:cake_4','Торт [осталось 4 кусочка]'},
{'cake:cake_5','Торт [осталось 5 кусочков]'},
{'chests_0gb_us:cobble','Укреплённый булыжником сундук'},
{'chests_0gb_us:dropbox','Dropbox'},
{'chests_0gb_us:secret','Тайный сундук'},
{'chests_0gb_us:shared','Общий сундук'},
{'chests_0gb_us:wifi','Беспроводной сундук'},
{'cooked_rat','Жареная крыса'},
{'default:apple','Яблоко'},
{'default:axe_bronze','Бронзовый топор'},
{'default:axe_diamond','Алмазный топор'},
{'default:axe_mese','Месеконовый топор'},
{'default:axe_steel','Стальной топор'},
{'default:axe_stone','Каменный топор'},
{'default:axe_wood','Древянный топор'},
{'default:book','Книга'},
{'default:bookshelf','Шкаф с книгами'},
{'default:brick','Кирпичный блок'},
{'default:bronze_ingot','Бронзовый слиток'},
{'default:bronzeblock','Бронзовый блок'},
{'default:cactus','Кактус'},
{'default:chest','Сундук'},
{'default:chest_locked','Сундук с замком'},
{'default:clay','Глиняный блок'},
{'default:clay_brick','Глинянный кирпич'},
{'default:clay_lump','Глина'},
{'default:cloud','Облако'},
{'default:coal_lump','Уголь'},
{'default:coalblock','Блок угля'},
{'default:cobble','Булыжник (коббл)'},
{'default:copper_ingot','Медный слиток'},
{'default:copper_lump','Медный самородок'},
{'default:copperblock','Медный блок'},
{'default:desert_sand','Пустынный песок'},
{'default:desert_stone','Пустынник'},
{'default:desert_stonebrick','Кирпичи из пустынника'},
{'default:diamond','Алмаз'},
{'default:diamondblock','Азмазный блок'},
{'default:dirt','Земля'},
{'default:dirt_with_grass','Земля с травой'},
{'default:dirt_with_grass_footsteps','Утопнанная земля с травой'},
{'default:dirt_with_snow','Земля со снегом'},
{'default:dry_shrub','Сухостой'},
{'default:fence_wood','Деревянный забор (обычный)'},
{'default:furnace','Печь'},
{'default:furnace_active','Печь (активная)'},
{'default:glass','Стекло'},
{'default:gold_ingot','Золотой слиток'},
{'default:gold_lump','Золотой самородок'},
{'default:goldblock','Золотой блок'},
{'default:grass_1','Трава'},
{'default:grass_2','Трава'},
{'default:grass_3','Трава'},
{'default:grass_4','Трава'},
{'default:grass_5','Трава'},
{'default:gravel','Гравий'},
{'default:ice','Лёд'},
{'default:iron_lump','Железный самородок'},
{'default:junglegrass','Густая трава'},
{'default:jungleleaves','Листва тропического дерева'},
{'default:junglesapling','Саженец тропического дерева'},
{'default:jungletree','Тропическое дерево'},
{'default:junglewood','Доски из тропического дерева'},
{'default:ladder','Лестница'},
{'default:lava_flowing','Текущая лава'},
{'default:lava_source','Источник лавы'},
{'default:leaves','Листья'},
{'default:mese','Блок Mесе'},
{'default:mese_crystal','Месе кристалл'},
{'default:mese_crystal_fragment','Осколок Месе кристалла'},
{'default:mossycobble','Замшелый булыжник'},
{'default:nyancat','Nyan Cat'},
{'default:nyancat_rainbow','Радуга Nyan Cat\'а'},
{'default:obsidian','Обсидиан'},
{'default:obsidian_glass','Обсидиановое стекло'},
{'default:obsidian_shard','Осколок обсидиана'},
{'default:paper','Бумага'},
{'default:papyrus','Тростник'},
{'default:pick_bronze','Бронзовая кирка'},
{'default:pick_diamond','Алмазная кирка'},
{'default:pick_mese','Месеконовая кирка'},
{'default:pick_steel','Стальная кирка'},
{'default:pick_stone','Каменная кирка'},
{'default:pick_wood','Деревянная кирка'},
{'default:rail','Рельсы'},
{'default:sand','Песок'},
{'default:sandstone','Песчаник'},
{'default:sandstonebrick','Кирпич из песчаника'},
{'default:sapling','Саженец'},
{'default:scorched_stuff','Обугленное нечто'},
{'default:shovel_bronze','Бронзовая лопата'},
{'default:shovel_diamond','Алмазная лопата'},
{'default:shovel_mese','Месеконовая лопата'},
{'default:shovel_steel','Стальная лдопата'},
{'default:shovel_stone','Каменная лопата'},
{'default:shovel_wood','Деревянная лопата'},
{'default:sign_wall','Табличка'},
{'default:snow','Снег'},
{'default:snowblock','Снежный блок'},
{'default:steel_ingot','Стальной слиток'},
{'default:steelblock','Стальной блок'},
{'default:stick','Палки'},
{'default:stone','Камень'},
{'default:stone_with_coal','Угольная руда'},
{'default:stone_with_copper','Медная руда'},
{'default:stone_with_diamond','Алмазная руда'},
{'default:stone_with_gold','Золотая руда'},
{'default:stone_with_iron','Железная руда'},
{'default:stone_with_mese','Месе руда'},
{'default:stonebrick','Каменный кирпич'},
{'default:sword_bronze','Бронзовый меч'},
{'default:sword_diamond','Алмазный меч'},
{'default:sword_mese','Месеконовый меч'},
{'default:sword_steel','Стальной меч'},
{'default:sword_stone','Каменный меч'},
{'default:sword_wood','Деревянный меч'},
{'default:torch','Факел'},
{'default:tree','Дерево'},
{'default:water_flowing','Текущая вода'},
{'default:water_source','Источник воды'},
{'default:wood','Доски'},
{'desert_uses:axe_desert_stone','Пустынниковый топор'},
{'desert_uses:desert_cobble','Пустынный булыжник'},
{'desert_uses:desert_furnace','Печь из пустынника'},
{'desert_uses:desert_furnace_active','Печь из пустынника'},
{'desert_uses:desert_sandstone','Пустынный песчаник'},
{'desert_uses:pick_desert_stone','Пустынниковая кирка'},
{'desert_uses:shovel_desert_stone','Пустынниковая лопата'},
{'desert_uses:sword_desert_stone','Пустынниковый меч'},
{'doors:door_glass','Стеклянная дверь'},
{'doors:door_glass_b_1',''},
{'doors:door_glass_b_2',''},
{'doors:door_glass_t_1',''},
{'doors:door_glass_t_2',''},
{'doors:door_obsidian_glass','Дверь из обсидианового стекла'},
{'doors:door_obsidian_glass_b_1',''},
{'doors:door_obsidian_glass_b_2',''},
{'doors:door_obsidian_glass_t_1',''},
{'doors:door_obsidian_glass_t_2',''},
{'doors:door_steel','Стальная дверь'},
{'doors:door_steel_b_1',''},
{'doors:door_steel_b_2',''},
{'doors:door_steel_t_1',''},
{'doors:door_steel_t_2',''},
{'doors:door_wood','Деревянная дверь'},
{'doors:door_wood_b_1',''},
{'doors:door_wood_b_2',''},
{'doors:door_wood_t_1',''},
{'doors:door_wood_t_2',''},
{'doors:trapdoor','Шлюз'},
{'doors:trapdoor_open',''},
{'dye:blue','Синий краситель'},
{'dye:brown','Коричневый краситель'},
{'dye:cyan','Голубой краситель'},
{'dye:dark_green','Тёмно-зелёный краситель'},
{'dye:dark_grey','Тёмно-серый краситель'},
{'dye:green','Зелёный краситель'},
{'dye:grey','Серый краситель'},
{'dye:magenta','Пурпурный краситель'},
{'dye:orange','Оранжевый краситель'},
{'dye:pink','Розовый краситель'},
{'dye:red','Красный краситель'},
{'dye:violet','Фиолетовый краситель'},
{'dye:white','Белый краситель'},
{'dye:yellow','Жёлтый краситель'},
{'farming:bread','Хлеб'},
{'farming:cotton_1',''},
{'farming:cotton_2',''},
{'farming:cotton_3',''},
{'farming:cotton_4',''},
{'farming:cotton_5',''},
{'farming:cotton_6',''},
{'farming:cotton_7',''},
{'farming:cotton_8',''},
{'farming:flour','Мука'},
{'farming:hoe_bronze','Бронзовая соха'},
{'farming:hoe_steel','Стальная соха'},
{'farming:hoe_stone','Каменная соха'},
{'farming:hoe_wood','Деревянная соха'},
{'farming:seed_cotton','Семена хлопка'},
{'farming:seed_wheat','Семена пшеницы'},
{'farming:soil','Почва'},
{'farming:soil_wet','Увлажнённая почва'},
{'farming:string','Нить'},
{'farming:wheat','Пшеница'},
{'farming:wheat_1',''},
{'farming:wheat_2',''},
{'farming:wheat_3',''},
{'farming:wheat_4',''},
{'farming:wheat_5',''},
{'farming:wheat_6',''},
{'farming:wheat_7',''},
{'farming:wheat_8',''},
{'fences:fence_wood','Деревянный забор'},
{'fences:fence_wood_1',''},
{'fences:fence_wood_11',''},
{'fences:fence_wood_12',''},
{'fences:fence_wood_13',''},
{'fences:fence_wood_14',''},
{'fences:fence_wood_2',''},
{'fences:fence_wood_21',''},
{'fences:fence_wood_22',''},
{'fences:fence_wood_23',''},
{'fences:fence_wood_24',''},
{'fences:fence_wood_3',''},
{'fences:fence_wood_32',''},
{'fences:fence_wood_33',''},
{'fences:fence_wood_34',''},
{'fences:fence_wood_35',''},
{'fences:fencegate','Деревянные ворота'},
{'fences:fencegate_open',''},
{'fire:basic_flame','Огонь'},
{'firefly','Светлячок'},
{'flint:flintstone','Кремень'},
{'flint:lighter','Зажигалка'},
{'flowers:dandelion_white','Пушистый одуванчик'},
{'flowers:dandelion_yellow','Жёлтый одуванчик'},
{'flowers:flower_pot','Горшок'},
{'flowers:geranium','Голубая герань'},
{'flowers:potted_dandelion_white','Горшок с пушистым одуванчиком'},
{'flowers:potted_dandelion_yellow','Горшок с жёлтым одуванчиком'},
{'flowers:potted_geranium','Горшок с голубой геранью'},
{'flowers:potted_rose','Горщок с розами'},
{'flowers:potted_tulip','Горшок с тюльпанами'},
{'flowers:potted_viola','Горшок с фиалками'},
{'flowers:rose','Роза'},
{'flowers:seaweed','Водоросли'},
{'flowers:seaweed_2','Водоросли'},
{'flowers:seaweed_3','Водоросли'},
{'flowers:seaweed_4','Водоросли'},
{'flowers:tulip','Тюльпан'},
{'flowers:viola','Фиалка'},
{'flowers:waterlily','Кувшинка'},
{'flowers:waterlily_225','Кувшинка'},
{'flowers:waterlily_45','Кувшинка'},
{'flowers:waterlily_675','Кувшинка'},
{'flowers:waterlily_s1','Кувшинка'},
{'flowers:waterlily_s2','Кувшинка'},
{'flowers:waterlily_s3','Кувшинка'},
{'flowers:waterlily_s4','Кувшинка'},
{'helicopter:blades','Вертушка'},
{'helicopter:cabin','Кабина вертолёта'},
{'helicopter:heli','Вертолёт'},
{'ignore','Нечто (Ах ты... Хакер, блин!)'},
{'junglegrass:medium','Густая трава (средняя)'},
{'junglegrass:short','Густая трава (короткая)'},
{'junglegrass:shortest','Густая трава (очень короткая)'},
{'locked_sign:sign_wall_locked','Защищённая табличка'},
{'memorandum:eraser','Ластик'},
{'memorandum:letter','Письмо'},
{'memorandum:letter_empty',''},
{'memorandum:letter_written',''},
{'memorandum:message','Послание в бутылке'},
{'mesecons:wire_00000000_off','Месекон'},
{'mesecons:wire_00000000_on','Провод ID:00000000'},
{'mesecons:wire_00010000_off','Месеконовый провод ID: 00010000)'},
{'mesecons:wire_00010000_on','Провод ID:00010000'},
{'mesecons:wire_00010001_off','Месеконовый провод ID: 00010001)'},
{'mesecons:wire_00010001_on','Провод ID:00010001'},
{'mesecons:wire_00100000_off','Месеконовый провод ID: 00100000)'},
{'mesecons:wire_00100000_on','Провод ID:00100000'},
{'mesecons:wire_00100010_off','Месеконовый провод ID: 00100010)'},
{'mesecons:wire_00100010_on','Провод ID:00100010'},
{'mesecons:wire_00110000_off','Месеконовый провод ID: 00110000)'},
{'mesecons:wire_00110000_on','Провод ID:00110000'},
{'mesecons:wire_00110001_off','Месеконовый провод ID: 00110001)'},
{'mesecons:wire_00110001_on','Провод ID:00110001'},
{'mesecons:wire_00110010_off','Месеконовый провод ID: 00110010)'},
{'mesecons:wire_00110010_on','Провод ID:00110010'},
{'mesecons:wire_00110011_off','Месеконовый провод ID: 00110011)'},
{'mesecons:wire_00110011_on','Провод ID:00110011'},
{'mesecons:wire_01000000_off','Месеконовый провод ID: 01000000)'},
{'mesecons:wire_01000000_on','Провод ID:01000000'},
{'mesecons:wire_01000100_off','Месеконовый провод ID: 01000100)'},
{'mesecons:wire_01000100_on','Провод ID:01000100'},
{'mesecons:wire_01010000_off','Месеконовый провод ID: 01010000)'},
{'mesecons:wire_01010000_on','Провод ID:01010000'},
{'mesecons:wire_01010001_off','Месеконовый провод ID: 01010001)'},
{'mesecons:wire_01010001_on','Провод ID:01010001'},
{'mesecons:wire_01010100_off','Месеконовый провод ID: 01010100)'},
{'mesecons:wire_01010100_on','Провод ID:01010100'},
{'mesecons:wire_01010101_off','Месеконовый провод ID: 01010101)'},
{'mesecons:wire_01010101_on','Провод ID:01010101'},
{'mesecons:wire_01100000_off','Месеконовый провод ID: 01100000)'},
{'mesecons:wire_01100000_on','Провод ID:01100000'},
{'mesecons:wire_01100010_off','Месеконовый провод ID: 01100010)'},
{'mesecons:wire_01100010_on','Провод ID:01100010'},
{'mesecons:wire_01100100_off','Месеконовый провод ID: 01100100)'},
{'mesecons:wire_01100100_on','Провод ID:01100100'},
{'mesecons:wire_01100110_off','Месеконовый провод ID: 01100110)'},
{'mesecons:wire_01100110_on','Провод ID:01100110'},
{'mesecons:wire_01110000_off','Месеконовый провод ID: 01110000)'},
{'mesecons:wire_01110000_on','Провод ID:01110000'},
{'mesecons:wire_01110001_off','Месеконовый провод ID: 01110001)'},
{'mesecons:wire_01110001_on','Провод ID:01110001'},
{'mesecons:wire_01110010_off','Месеконовый провод ID: 01110010)'},
{'mesecons:wire_01110010_on','Провод ID:01110010'},
{'mesecons:wire_01110011_off','Месеконовый провод ID: 01110011)'},
{'mesecons:wire_01110011_on','Провод ID:01110011'},
{'mesecons:wire_01110100_off','Месеконовый провод ID: 01110100)'},
{'mesecons:wire_01110100_on','Провод ID:01110100'},
{'mesecons:wire_01110101_off','Месеконовый провод ID: 01110101)'},
{'mesecons:wire_01110101_on','Провод ID:01110101'},
{'mesecons:wire_01110110_off','Месеконовый провод ID: 01110110)'},
{'mesecons:wire_01110110_on','Провод ID:01110110'},
{'mesecons:wire_01110111_off','Месеконовый провод ID: 01110111)'},
{'mesecons:wire_01110111_on','Провод ID:01110111'},
{'mesecons:wire_10000000_off','Месеконовый провод ID: 10000000)'},
{'mesecons:wire_10000000_on','Провод ID:10000000'},
{'mesecons:wire_10001000_off','Месеконовый провод ID: 10001000)'},
{'mesecons:wire_10001000_on','Провод ID:10001000'},
{'mesecons:wire_10010000_off','Месеконовый провод ID: 10010000)'},
{'mesecons:wire_10010000_on','Провод ID:10010000'},
{'mesecons:wire_10010001_off','Месеконовый провод ID: 10010001)'},
{'mesecons:wire_10010001_on','Провод ID:10010001'},
{'mesecons:wire_10011000_off','Месеконовый провод ID: 10011000)'},
{'mesecons:wire_10011000_on','Провод ID:10011000'},
{'mesecons:wire_10011001_off','Месеконовый провод ID: 10011001)'},
{'mesecons:wire_10011001_on','Провод ID:10011001'},
{'mesecons:wire_10100000_off','Месеконовый провод ID: 10100000)'},
{'mesecons:wire_10100000_on','Провод ID:10100000'},
{'mesecons:wire_10100010_off','Месеконовый провод ID: 10100010)'},
{'mesecons:wire_10100010_on','Провод ID:10100010'},
{'mesecons:wire_10101000_off','Месеконовый провод ID: 10101000)'},
{'mesecons:wire_10101000_on','Провод ID:10101000'},
{'mesecons:wire_10101010_off','Месеконовый провод ID: 10101010)'},
{'mesecons:wire_10101010_on','Провод ID:10101010'},
{'mesecons:wire_10110000_off','Месеконовый провод ID: 10110000)'},
{'mesecons:wire_10110000_on','Провод ID:10110000'},
{'mesecons:wire_10110001_off','Месеконовый провод ID: 10110001)'},
{'mesecons:wire_10110001_on','Провод ID:10110001'},
{'mesecons:wire_10110010_off','Месеконовый провод ID: 10110010)'},
{'mesecons:wire_10110010_on','Провод ID:10110010'},
{'mesecons:wire_10110011_off','Месеконовый провод ID: 10110011)'},
{'mesecons:wire_10110011_on','Провод ID:10110011'},
{'mesecons:wire_10111000_off','Месеконовый провод ID: 10111000)'},
{'mesecons:wire_10111000_on','Провод ID:10111000'},
{'mesecons:wire_10111001_off','Месеконовый провод ID: 10111001)'},
{'mesecons:wire_10111001_on','Провод ID:10111001'},
{'mesecons:wire_10111010_off','Месеконовый провод ID: 10111010)'},
{'mesecons:wire_10111010_on','Провод ID:10111010'},
{'mesecons:wire_10111011_off','Месеконовый провод ID: 10111011)'},
{'mesecons:wire_10111011_on','Провод ID:10111011'},
{'mesecons:wire_11000000_off','Месеконовый провод ID: 11000000)'},
{'mesecons:wire_11000000_on','Провод ID:11000000'},
{'mesecons:wire_11000100_off','Месеконовый провод ID: 11000100)'},
{'mesecons:wire_11000100_on','Провод ID:11000100'},
{'mesecons:wire_11001000_off','Месеконовый провод ID: 11001000)'},
{'mesecons:wire_11001000_on','Провод ID:11001000'},
{'mesecons:wire_11001100_off','Месеконовый провод ID: 11001100)'},
{'mesecons:wire_11001100_on','Провод ID:11001100'},
{'mesecons:wire_11010000_off','Месеконовый провод ID: 11010000)'},
{'mesecons:wire_11010000_on','Провод ID:11010000'},
{'mesecons:wire_11010001_off','Месеконовый провод ID: 11010001)'},
{'mesecons:wire_11010001_on','Провод ID:11010001'},
{'mesecons:wire_11010100_off','Месеконовый провод ID: 11010100)'},
{'mesecons:wire_11010100_on','Провод ID:11010100'},
{'mesecons:wire_11010101_off','Месеконовый провод ID: 11010101)'},
{'mesecons:wire_11010101_on','Провод ID:11010101'},
{'mesecons:wire_11011000_off','Месеконовый провод ID: 11011000)'},
{'mesecons:wire_11011000_on','Провод ID:11011000'},
{'mesecons:wire_11011001_off','Месеконовый провод ID: 11011001)'},
{'mesecons:wire_11011001_on','Провод ID:11011001'},
{'mesecons:wire_11011100_off','Месеконовый провод ID: 11011100)'},
{'mesecons:wire_11011100_on','Провод ID:11011100'},
{'mesecons:wire_11011101_off','Месеконовый провод ID: 11011101)'},
{'mesecons:wire_11011101_on','Провод ID:11011101'},
{'mesecons:wire_11100000_off','Месеконовый провод ID: 11100000)'},
{'mesecons:wire_11100000_on','Провод ID:11100000'},
{'mesecons:wire_11100010_off','Месеконовый провод ID: 11100010)'},
{'mesecons:wire_11100010_on','Провод ID:11100010'},
{'mesecons:wire_11100100_off','Месеконовый провод ID: 11100100)'},
{'mesecons:wire_11100100_on','Провод ID:11100100'},
{'mesecons:wire_11100110_off','Месеконовый провод ID: 11100110)'},
{'mesecons:wire_11100110_on','Провод ID:11100110'},
{'mesecons:wire_11101000_off','Месеконовый провод ID: 11101000)'},
{'mesecons:wire_11101000_on','Провод ID:11101000'},
{'mesecons:wire_11101010_off','Месеконовый провод ID: 11101010)'},
{'mesecons:wire_11101010_on','Провод ID:11101010'},
{'mesecons:wire_11101100_off','Месеконовый провод ID: 11101100)'},
{'mesecons:wire_11101100_on','Провод ID:11101100'},
{'mesecons:wire_11101110_off','Месеконовый провод ID: 11101110)'},
{'mesecons:wire_11101110_on','Провод ID:11101110'},
{'mesecons:wire_11110000_off','Месеконовый провод ID: 11110000)'},
{'mesecons:wire_11110000_on','Провод ID:11110000'},
{'mesecons:wire_11110001_off','Месеконовый провод ID: 11110001)'},
{'mesecons:wire_11110001_on','Провод ID:11110001'},
{'mesecons:wire_11110010_off','Месеконовый провод ID: 11110010)'},
{'mesecons:wire_11110010_on','Провод ID:11110010'},
{'mesecons:wire_11110011_off','Месеконовый провод ID: 11110011)'},
{'mesecons:wire_11110011_on','Провод ID:11110011'},
{'mesecons:wire_11110100_off','Месеконовый провод ID: 11110100)'},
{'mesecons:wire_11110100_on','Провод ID:11110100'},
{'mesecons:wire_11110101_off','Месеконовый провод ID: 11110101)'},
{'mesecons:wire_11110101_on','Провод ID:11110101'},
{'mesecons:wire_11110110_off','Месеконовый провод ID: 11110110)'},
{'mesecons:wire_11110110_on','Провод ID:11110110'},
{'mesecons:wire_11110111_off','Месеконовый провод ID: 11110111)'},
{'mesecons:wire_11110111_on','Провод ID:11110111'},
{'mesecons:wire_11111000_off','Месеконовый провод ID: 11111000)'},
{'mesecons:wire_11111000_on','Провод ID:11111000'},
{'mesecons:wire_11111001_off','Месеконовый провод ID: 11111001)'},
{'mesecons:wire_11111001_on','Провод ID:11111001'},
{'mesecons:wire_11111010_off','Месеконовый провод ID: 11111010)'},
{'mesecons:wire_11111010_on','Провод ID:11111010'},
{'mesecons:wire_11111011_off','Месеконовый провод ID: 11111011)'},
{'mesecons:wire_11111011_on','Провод ID:11111011'},
{'mesecons:wire_11111100_off','Месеконовый провод ID: 11111100)'},
{'mesecons:wire_11111100_on','Провод ID:11111100'},
{'mesecons:wire_11111101_off','Месеконовый провод ID: 11111101)'},
{'mesecons:wire_11111101_on','Провод ID:11111101'},
{'mesecons:wire_11111110_off','Месеконовый провод ID: 11111110)'},
{'mesecons:wire_11111110_on','Провод ID:11111110'},
{'mesecons:wire_11111111_off','Месеконовый провод ID: 11111111)'},
{'mesecons:wire_11111111_on','Провод ID:11111111'},
{'mesecons_blinkyplant:blinky_plant','Мерцающее растение'},
{'mesecons_blinkyplant:blinky_plant_off','Мерцающее растение'},
{'mesecons_blinkyplant:blinky_plant_on','Мерцающее растение'},
{'mesecons_button:button_off','Кнопка'},
{'mesecons_button:button_on','Кнопка'},
{'mesecons_commandblock:commandblock_off','Командный блок'},
{'mesecons_commandblock:commandblock_on',''},
{'mesecons_delayer:delayer_off_1','Задерживающий триггер'},
{'mesecons_delayer:delayer_off_2','Задерживающий триггер'},
{'mesecons_delayer:delayer_off_3','Задерживающий триггер'},
{'mesecons_delayer:delayer_off_4','Задерживающий триггер'},
{'mesecons_delayer:delayer_on_1','Ах ты... Хакер, блин!'},
{'mesecons_delayer:delayer_on_2','Ах ты... Хакер, блин!'},
{'mesecons_delayer:delayer_on_3','Ах ты... Хакер, блин!'},
{'mesecons_delayer:delayer_on_4','Ах ты... Хакер, блин!'},
{'mesecons_detector:object_detector_off','Детектор игрока'},
{'mesecons_detector:object_detector_on',''},
{'mesecons_extrawires:corner_off','Месеконовый уголок'},
{'mesecons_extrawires:corner_on',''},
{'mesecons_extrawires:crossover_01','Ах ты... Хакер, блин!'},
{'mesecons_extrawires:crossover_10','Ах ты... Хакер, блин!'},
{'mesecons_extrawires:crossover_off','Заизолированый кроссовер'},
{'mesecons_extrawires:crossover_on','Ах ты... Хакер, блин!'},
{'mesecons_extrawires:mese_powered',''},
{'mesecons_extrawires:tjunction_off','T-соединение'},
{'mesecons_extrawires:tjunction_on',''},
{'mesecons_extrawires:vertical_bottom_off','Стоячий месекон'},
{'mesecons_extrawires:vertical_bottom_on','Стоячий месекон'},
{'mesecons_extrawires:vertical_off','Стоячий месекон'},
{'mesecons_extrawires:vertical_on','Стоячий месекон'},
{'mesecons_extrawires:vertical_top_off','Стоячий месекон'},
{'mesecons_extrawires:vertical_top_on','Стоячий месекон'},
{'mesecons_gates:and_off','AND гейт'},
{'mesecons_gates:and_on','Ах ты... Хакер, блин!'},
{'mesecons_gates:diode_off','Диод'},
{'mesecons_gates:diode_on','Ах ты... Хакер, блин!'},
{'mesecons_gates:nand_off','NAND гейт'},
{'mesecons_gates:nand_on','Ах ты... Хакер, блин!'},
{'mesecons_gates:not_off','NOT гейт'},
{'mesecons_gates:not_on','Ах ты... Хакер, блин!'},
{'mesecons_gates:xor_off','XOR гейт'},
{'mesecons_gates:xor_on','Ах ты... Хакер, блин!'},
{'mesecons_hydroturbine:hydro_turbine_off','Водяная турбина'},
{'mesecons_hydroturbine:hydro_turbine_on','Водяная турбина'},
{'mesecons_insulated:insulated_off','Заизолированный месекон'},
{'mesecons_insulated:insulated_on','Заизолированный месекон'},
{'mesecons_lamp:lamp_off','Меселапма'},
{'mesecons_lamp:lamp_on',''},
{'mesecons_lightstone:lightstone_blue_off','Синий светящийся камень'},
{'mesecons_lightstone:lightstone_blue_on',''},
{'mesecons_lightstone:lightstone_darkgray_off','Тёмно-серый светящийся камень'},
{'mesecons_lightstone:lightstone_darkgray_on',''},
{'mesecons_lightstone:lightstone_gray_off','Серый светящийся камень'},
{'mesecons_lightstone:lightstone_gray_on',''},
{'mesecons_lightstone:lightstone_green_off','Зелёный светящийся камень'},
{'mesecons_lightstone:lightstone_green_on',''},
{'mesecons_lightstone:lightstone_red_off','Красный светящийся камень'},
{'mesecons_lightstone:lightstone_red_on',''},
{'mesecons_lightstone:lightstone_yellow_off','Жёлтый светящийся камень'},
{'mesecons_lightstone:lightstone_yellow_on',''},
{'mesecons_luacontroller:luacontroller_burnt',''},
{'mesecons_luacontroller:luacontroller0000','Lua контроллер'},
{'mesecons_luacontroller:luacontroller0001','Lua контроллер'},
{'mesecons_luacontroller:luacontroller0010','Lua контроллер'},
{'mesecons_luacontroller:luacontroller0011','Lua контроллер'},
{'mesecons_luacontroller:luacontroller0100','Lua контроллер'},
{'mesecons_luacontroller:luacontroller0101','Lua контроллер'},
{'mesecons_luacontroller:luacontroller0110','Lua контроллер'},
{'mesecons_luacontroller:luacontroller0111','Lua контроллер'},
{'mesecons_luacontroller:luacontroller1000','Lua контроллер'},
{'mesecons_luacontroller:luacontroller1001','Lua контроллер'},
{'mesecons_luacontroller:luacontroller1010','Lua контроллер'},
{'mesecons_luacontroller:luacontroller1011','Lua контроллер'},
{'mesecons_luacontroller:luacontroller1101','Lua контроллер'},
{'mesecons_luacontroller:luacontroller1110','Lua контроллер'},
{'mesecons_luacontroller:luacontroller1111','Lua контроллер'},
{'mesecons_materials:fiber','Фибра'},
{'mesecons_materials:glue','Клейкое вещество'},
{'mesecons_materials:silicon','Силикон'},
{'mesecons_microcontroller:microcontroller0000','Микроконтроллер'},
{'mesecons_microcontroller:microcontroller0001','Микроконтроллер'},
{'mesecons_microcontroller:microcontroller0010','Микроконтроллер'},
{'mesecons_microcontroller:microcontroller0011','Микроконтроллер'},
{'mesecons_microcontroller:microcontroller0100','Микроконтроллер'},
{'mesecons_microcontroller:microcontroller0101','Микроконтроллер'},
{'mesecons_microcontroller:microcontroller0110','Микроконтроллер'},
{'mesecons_microcontroller:microcontroller0111','Микроконтроллер'},
{'mesecons_microcontroller:microcontroller1000','Микроконтроллер'},
{'mesecons_microcontroller:microcontroller1001','Микроконтроллер'},
{'mesecons_microcontroller:microcontroller1010','Микроконтроллер'},
{'mesecons_microcontroller:microcontroller1011','Микроконтроллер'},
{'mesecons_microcontroller:microcontroller1100','Микроконтроллер'},
{'mesecons_microcontroller:microcontroller1101','Микроконтроллер'},
{'mesecons_microcontroller:microcontroller1110','Микроконтроллер'},
{'mesecons_microcontroller:microcontroller1111','Микроконтроллер'},
{'mesecons_movestones:movestone','Переместитель'},
{'mesecons_movestones:sticky_movestone','Липкий переместитель'},
{'mesecons_noteblock:noteblock','Нотный блок'},
{'mesecons_pistons:piston_down_normal_off',''},
{'mesecons_pistons:piston_down_normal_on',''},
{'mesecons_pistons:piston_down_pusher_normal',''},
{'mesecons_pistons:piston_down_pusher_sticky',''},
{'mesecons_pistons:piston_down_sticky_off',''},
{'mesecons_pistons:piston_down_sticky_on',''},
{'mesecons_pistons:piston_normal_off','Поршень'},
{'mesecons_pistons:piston_normal_on',''},
{'mesecons_pistons:piston_pusher_normal',''},
{'mesecons_pistons:piston_pusher_sticky',''},
{'mesecons_pistons:piston_sticky_off','Липкий поршень'},
{'mesecons_pistons:piston_sticky_on',''},
{'mesecons_pistons:piston_up_normal_off',''},
{'mesecons_pistons:piston_up_normal_on',''},
{'mesecons_pistons:piston_up_pusher_normal',''},
{'mesecons_pistons:piston_up_pusher_sticky',''},
{'mesecons_pistons:piston_up_sticky_off',''},
{'mesecons_pistons:piston_up_sticky_on',''},
{'mesecons_powerplant:power_plant','Светотрава'},
{'mesecons_pressureplates:pressure_plate_stone_off','Каменная нажимная плита'},
{'mesecons_pressureplates:pressure_plate_stone_on',''},
{'mesecons_pressureplates:pressure_plate_wood_off','Деревянная нажимная плита'},
{'mesecons_pressureplates:pressure_plate_wood_on',''},
{'mesecons_random:ghoststone','Призрачный камень'},
{'mesecons_random:ghoststone_active',''},
{'mesecons_random:removestone','Саморазрушающийся камень'},
{'mesecons_receiver:receiver_off','Ах ты... Хакер, блин!'},
{'mesecons_receiver:receiver_on','Ах ты... Хакер, блин!'},
{'mesecons_solarpanel:solar_panel_off','Солнечная панель'},
{'mesecons_solarpanel:solar_panel_on','Солнечная панель'},
{'mesecons_switch:mesecon_switch_off','Выключатель'},
{'mesecons_switch:mesecon_switch_on','Выключатель'},
{'mesecons_torch:mesecon_torch_off','Месефакел'},
{'mesecons_torch:mesecon_torch_on','Месефакел'},
{'mesecons_walllever:wall_lever_off','Рычаг'},
{'mesecons_walllever:wall_lever_on','Рычаг'},
{'moreores:axe_mithril','Митриловый топор'},
{'moreores:axe_silver','Серебрянный топор'},
{'moreores:copper_rail','Медные рельсы'},
{'moreores:hoe_mithril','Митриловая соха'},
{'moreores:hoe_silver','Сербрянная соха'},
{'moreores:mineral_mithril','Митриловая руда'},
{'moreores:mineral_silver','Серебрянная руда'},
{'moreores:mineral_tin','Оловянная руда'},
{'moreores:mithril_block','Митриловый блок'},
{'moreores:mithril_ingot','Митриловый слиток'},
{'moreores:mithril_lump','Митриловый самородок'},
{'moreores:pick_mithril','Митриловая кирка'},
{'moreores:pick_silver','Серебрянная кирка'},
{'moreores:shovel_mithril','Митрилдовая лопата'},
{'moreores:shovel_silver','Серебрянная лопата'},
{'moreores:silver_block','Серебрянный блок'},
{'moreores:silver_ingot','Серебрянный слиток'},
{'moreores:silver_lump','Серебрянный самородок'},
{'moreores:sword_mithril','Миториловый меч'},
{'moreores:sword_silver','Серебряный меч'},
{'moreores:tin_block','Блок олова'},
{'moreores:tin_lump','Оловянный самородок'},
{'moretrees:acorn','Шишка'},
{'moretrees:acorn_muffin','Acorn Muffin'},
{'moretrees:acorn_muffin_batter','Acorn Muffin batter'},
{'moretrees:apple_tree_leaves','Листва яблони'},
{'moretrees:apple_tree_planks','Яблоневые доски'},
{'moretrees:apple_tree_sapling','Саженец яблони'},
{'moretrees:apple_tree_sapling_ongen','Саженец яблони'},
{'moretrees:apple_tree_trunk','Яблоня'},
{'moretrees:beech_leaves','Листва бука'},
{'moretrees:beech_planks','Буковые доски'},
{'moretrees:beech_sapling','Саженец бука'},
{'moretrees:beech_sapling_ongen','Саженец бука'},
{'moretrees:beech_trunk','Бук'},
{'moretrees:birch_leaves','Листва берёзы'},
{'moretrees:birch_planks','Берёзовые доски'},
{'moretrees:birch_sapling','Саженец берёзы'},
{'moretrees:birch_sapling_ongen','Саженец берёзы'},
{'moretrees:birch_trunk','Берёза'},
{'moretrees:coconut','Кокос'},
{'moretrees:coconut_milk','Кокосовое молоко'},
{'moretrees:fir_cone','Шишка'},
{'moretrees:fir_leaves','Иголки пихты дугласа'},
{'moretrees:fir_leaves_bright','Иколки пихты дугласа (светлые)'},
{'moretrees:fir_nuts','Жареные еловые орешки'},
{'moretrees:fir_planks','Доски из пихты дугласа'},
{'moretrees:fir_sapling','Саженец пихты дугласа'},
{'moretrees:fir_sapling_ongen','Саженец пихты дугласа'},
{'moretrees:fir_trunk','Пихта Дугласа'},
{'moretrees:jungletree_leaves_green','Листва тропического дерева (зелёная)'},
{'moretrees:jungletree_leaves_red','Листва тропического дерева (красная)'},
{'moretrees:jungletree_leaves_yellow','Листва тропического дерева (жёлтая)'},
{'moretrees:jungletree_sapling','Саженец тропического дерева'},
{'moretrees:jungletree_sapling_ongen','Саженец тропического дерева'},
{'moretrees:oak_leaves','Листва дуба'},
{'moretrees:oak_planks','Дубовые доски'},
{'moretrees:oak_sapling','Саженец дуба'},
{'moretrees:oak_sapling_ongen','Саженец дуба'},
{'moretrees:oak_trunk','Дуб'},
{'moretrees:palm_leaves','Пальповые листья'},
{'moretrees:palm_planks','Доски из пальмы'},
{'moretrees:palm_sapling','Саженец пальмы'},
{'moretrees:palm_sapling_ongen','Саженец пальмы'},
{'moretrees:palm_trunk','Пальма'},
{'moretrees:pine_cone','Сосновая шишка'},
{'moretrees:pine_leaves','Сосновые иголки'},
{'moretrees:pine_nuts','Жареные кедровые орешки'},
{'moretrees:pine_planks','Сосновые доски'},
{'moretrees:pine_sapling','Саженец сосны'},
{'moretrees:pine_sapling_ongen','Саженец сосны'},
{'moretrees:pine_trunk','Сосна'},
{'moretrees:raw_coconut','Кокос'},
{'moretrees:rubber_tree_leaves','Листва каучукового дерева'},
{'moretrees:rubber_tree_planks','Доски из каучукового дерева'},
{'moretrees:rubber_tree_sapling','Краник'},
{'moretrees:rubber_tree_sapling_ongen','Саженец каучукового дерева'},
{'moretrees:rubber_tree_trunk','Каучуковое дерево'},
{'moretrees:rubber_tree_trunk_empty','Каучуковое дерево (пустое)'},
{'moretrees:sequoia_leaves','Листва гигантской секвойи'},
{'moretrees:sequoia_planks','Доски из гигантской секвоий'},
{'moretrees:sequoia_sapling','Саженец гигантской секвойи'},
{'moretrees:sequoia_sapling_ongen','Саженец гигантской секвойи'},
{'moretrees:sequoia_trunk','Гигантская секвойя'},
{'moretrees:spruce_cone','Еловая шишка'},
{'moretrees:spruce_leaves','Еловые иголки'},
{'moretrees:spruce_planks','Еловые доски'},
{'moretrees:spruce_sapling','Саженец ели'},
{'moretrees:spruce_sapling_ongen','Саженец ели'},
{'moretrees:spruce_trunk','Ель'},
{'moretrees:willow_leaves','Листья ивового дерева'},
{'moretrees:willow_planks','Ивовые доски'},
{'moretrees:willow_sapling','Саженец ивы'},
{'moretrees:willow_sapling_ongen','Саженец ивового дерева'},
{'moretrees:willow_trunk','Ивовое дерево'},
{'peaceful_npc:spawner_npc_def','Портал NPC (обычный)'},
{'peaceful_npc:spawner_npc_dwarf','Портал NPC (дварф)'},
{'peaceful_npc:spawner_npc_fast','Портал NPC (быстрый)'},
{'peaceful_npc:summoner_npc_def','Призыватель NPC (обычный)'},
{'peaceful_npc:summoner_npc_dwarf','Призыватель NPC (дварф)'},
{'peaceful_npc:summoner_npc_fast','Призыватель NPC (быстрый)'},
{'potions:glass_bottle','Бутылка'},
{'potionspack:antigravity','Антигравитация Зелье'},
{'potionspack:antigravityii','Антигравитация II Зелье'},
{'potionspack:confusion','Путаница Зелье'},
{'potionspack:harming','Урон Зелье'},
{'potionspack:harmingii','Урон II Зелье'},
{'potionspack:instanthealth','Лечение Зелье'},
{'potionspack:instanthealthii','Лечение II Зелье'},
{'potionspack:inversion','Обращение Зелье'},
{'potionspack:regen','Регенерация Зелье'},
{'potionspack:regenii','Регенерация II Зелье'},
{'potionspack:speed','Скорость Зелье'},
{'potionspack:speedii','Скорость II Зелье'},
{'potionspack:whatwillthisdo','Чтозанахрен зелье'},
{'rat','Крыса'},
{'screwdriver:screwdriver','Отвёртка'},
{'screwdriver:screwdriver1','Отвёртка в режиме 1'},
{'screwdriver:screwdriver2','Отвёртка в режиме 2'},
{'screwdriver:screwdriver3','Отвёртка в режиме 3'},
{'screwdriver:screwdriver4','Отвёртка в режиме 4'},
{'shields:shield_bronze','Бронзовый щит'},
{'shields:shield_diamond','Алмазный щит'},
{'shields:shield_mithril','Митриловый щит'},
{'shields:shield_steel','Стальной щит'},
{'shields:shield_wood','Деревянный щит'},
{'signs:sign_yard',''},
{'signs:sign_yard',''},
{'specialties:axe_bronze_feller','Бронзовый топор (+Автосрубание)'},
{'specialties:axe_bronze_superheat','Бронзовый топор (+Плавка)'},
{'specialties:axe_diamond_feller','Алмазный топор (+Автосрубание)'},
{'specialties:axe_diamond_superheat','Алмазный топор (+Плавка)'},
{'specialties:axe_mese_feller','Месеконовый топор (+Автосрубание)'},
{'specialties:axe_mese_superheat','Месеконовый топор (+Плавка)'},
{'specialties:axe_steel_feller','Стальной топор (+Автосрубание)'},
{'specialties:axe_steel_superheat','Стальной топор (+Плавка)'},
{'specialties:axe_stone_feller','Каменный топор (+Автосрубание)'},
{'specialties:axe_stone_superheat','Каменный топор (+Плавка)'},
{'specialties:axe_wood_feller','Деревянный топор (+Автосрубание)'},
{'specialties:axe_wood_superheat','Деревянный топор (+Плавка)'},
{'specialties:condenser','Конденсатор'},
{'specialties:hoe_bronze_greenthumb','Бронзоввая соха (+Садовник)'},
{'specialties:hoe_steel_greenthumb','Стальная соха (+Садовник)'},
{'specialties:hoe_stone_greenthumb','Каменная соха (+Садовник)'},
{'specialties:hoe_wood_greenthumb','Деревянная соха (+Садовник)'},
{'specialties:pick_bronze_superheat','Бронзовая кирка (+Плавка)'},
{'specialties:pick_diamond_superheat','Алмазная кирка (+Плавка)'},
{'specialties:pick_mese_superheat','Месеконовая кирка (+Плавка)'},
{'specialties:pick_steel_superheat','Стальная кирка (+Плавка)'},
{'specialties:pick_stone_superheat','Каменная кирка (+Плавка)'},
{'specialties:pick_wood_superheat','Деревянная кирка (+Плавка)'},
{'specialties:shovel_bronze_superheat','Бронзовая лопата (+Плавка)'},
{'specialties:shovel_diamond_superheat','Алмазная лопата (+Плавка)'},
{'specialties:shovel_mese_superheat','Месеконовая лопата (+Плавка)'},
{'specialties:shovel_steel_superheat','Стальная лопата (+Плавка)'},
{'specialties:shovel_stone_superheat','Каменная лопата (+Плавка)'},
{'specialties:shovel_wood_superheat','Деревянная лопата (+Плавка)'},
{'sponge:fake_air','Поддельный воздух'},
{'sponge:iron_sponge','Железная губка'},
{'sponge:sponge','Губка'},
{'stairs:slab_brick','Кирпичная плита'},
{'stairs:slab_brickupside_down',''},
{'stairs:slab_cobble','Плита из булыжника'},
{'stairs:slab_cobbleupside_down',''},
{'stairs:slab_desert_cobble','Плита из пустынного булыжника'},
{'stairs:slab_desert_cobbleupside_down',''},
{'stairs:slab_desert_sandstone','Плита из пустынного песчаника'},
{'stairs:slab_desert_sandstoneupside_down',''},
{'stairs:slab_desert_stone','Плита из пустынника'},
{'stairs:slab_desert_stoneupside_down',''},
{'stairs:slab_junglewood','Плита из тропического дерева'},
{'stairs:slab_junglewoodupside_down',''},
{'stairs:slab_sandstone','Плита из песчаника'},
{'stairs:slab_sandstoneupside_down',''},
{'stairs:slab_stone','Каменная плита'},
{'stairs:slab_stonebrick','Каменнокирпичная плита'},
{'stairs:slab_stonebrickupside_down',''},
{'stairs:slab_stoneupside_down',''},
{'stairs:slab_wood','Деревянная плита'},
{'stairs:slab_woodupside_down',''},
{'stairs:stair_brick','Кирпичные ступени'},
{'stairs:stair_brickupside_down',''},
{'stairs:stair_cobble','Ступени из булыжника'},
{'stairs:stair_cobbleupside_down',''},
{'stairs:stair_desert_cobble','Ступени из пустынного булыжника'},
{'stairs:stair_desert_cobbleupside_down',''},
{'stairs:stair_desert_sandstone','Стумени из пустынного песчаника'},
{'stairs:stair_desert_sandstoneupside_down',''},
{'stairs:stair_desert_stone','Ступени из пустынника'},
{'stairs:stair_desert_stoneupside_down',''},
{'stairs:stair_junglewood','Ступени из тропического дерева'},
{'stairs:stair_junglewoodupside_down',''},
{'stairs:stair_sandstone','Ступени из песчаника'},
{'stairs:stair_sandstoneupside_down',''},
{'stairs:stair_stone','Ступени из камня'},
{'stairs:stair_stonebrick','Каменнокирпичные ступени'},
{'stairs:stair_stonebrickupside_down',''},
{'stairs:stair_stoneupside_down',''},
{'stairs:stair_wood','Деревянные ступени'},
{'stairs:stair_woodupside_down',''},
{'throwing:arrow','Стрела'},
{'throwing:arrow_box',''},
{'throwing:arrow_build','Стрела-строитель'},
{'throwing:arrow_build_box',''},
{'throwing:arrow_dig','Стрела-экскаватор'},
{'throwing:arrow_dig_box',''},
{'throwing:arrow_fire','Огненная стрела'},
{'throwing:arrow_fire_box',''},
{'throwing:arrow_teleport','Стрела телепортации'},
{'throwing:arrow_teleport_box',''},
{'throwing:bow_steel','Стальной лук'},
{'throwing:bow_stone','Каменный лук'},
{'throwing:bow_wood','Деревянный лук'},
{'throwing:light',''},
{'tnt:tnt','Динамит'},
{'ufos:box','НЛО бокс (Ах ты... Хакер, блин!)'},
{'ufos:furnace','Зарядное устройство для НЛО'},
{'ufos:furnace_active','Зарядное устройство для НЛО'},
{'ufos:ufo','НЛО'},
{'unknown','Непойми что :('},
{'vessels:drinking_glass','Стакан (пустой)'},
{'vessels:glass_bottle','Бутылка'},
{'vessels:glass_fragments','Кучка осколков'},
{'vessels:steel_bottle','Фляга (пустая)'},
{'wool:black','Чёрная шерсть'},
{'wool:blue','Синяя шерсть'},
{'wool:brown','Коричневая шерсть'},
{'wool:cyan','Голубая шерсть'},
{'wool:dark_green','Тёмно-зелёная шерсть'},
{'wool:dark_grey','Тёмно-серая шерсть'},
{'wool:green','Зелёная шерсть'},
{'wool:grey','Серая шерсть'},
{'wool:magenta','Пурпурная шерсть'},
{'wool:orange','Оранжевая шерсть'},
{'wool:pink','Розовая шерсть'},
{'wool:red','Красная шерсть'},
{'wool:violet','Фиолетовая шерсть'},
{'wool:white','Белая шерсть'},
{'wool:yellow','Жёлтая шерсть'},
{'workbench:workbench','Верстак'},
-- 2nd addition (lazyyme)
{'animal_chicken:chick_f','Цыплёнок (курица)'},
{'animal_chicken:chick_m','Цыплёнок (петух)'},
{'animal_chicken:chicken','Циплёнок'},
{'animal_chicken:rooster','Петух'},
{'animal_clownfish:clownfish','Рыба-клоун'},
{'animal_cow:baby_calf_f','Телёнок (корова)'},
{'animal_cow:baby_calf_m','Телёнок (бык)'},
{'animal_cow:cow','Корова'},
{'animal_creeper:creeper','Бабах...'},
{'animal_dm:dm','Повелитель подземелий (MOBF)'},
{'animal_gull:gull','Гуль'},
{'animal_rat:rat','Крыса'},
{'animal_wolf:tamed_wolf','Приручённый волк'},
{'animal_wolf:wolf','Волк'},
{'animalmaterials:bone','Кость'},
{'animalmaterials:coat_cattle','Телячья шкура'},
{'animalmaterials:contract','Контракт'},
{'animalmaterials:deer_horns','Панты'},
{'animalmaterials:egg_big','Яйцо (ВС)'},
{'animalmaterials:egg','Яйцо (С2)'},
{'animalmaterials:feather','Перо'},
{'animalmaterials:fish_bluewhite','Рыба (полосатик)'},
{'animalmaterials:fish_clownfish','Рыба (рыба-клоун)'},
{'animalmaterials:fur_deer','Олений мех'},
{'animalmaterials:fur','Мех'},
{'animalmaterials:ivory','Ivory'},
{'animalmaterials:lasso','Лассо'},
{'animalmaterials:meat_beef','Сырая говядина'},
{'animalmaterials:meat_chicken','Сырая курица'},
{'animalmaterials:meat_lamb','Баран'},
{'animalmaterials:meat_ostrich','Страусятина'},
{'animalmaterials:meat_pork','Сырая швайнина'},
{'animalmaterials:meat_raw','Сырое мясо'},
{'animalmaterials:meat_toxic','Токсичная плоть'},
{'animalmaterials:meat_undead','Гнилая плоть'},
{'animalmaterials:meat_venison','Вяленое мясо'},
{'animalmaterials:milk','Молоко'},
{'animalmaterials:net','Сеть'},
{'animalmaterials:saddle','Седло'},
{'animalmaterials:scale_blue','Синяя чешуйка'},
{'animalmaterials:scale_golden','Золотая чешуйка'},
{'animalmaterials:scale_grey','Серая чешуйка'},
{'animalmaterials:scale_white','Белая чешуйка'},
{'animalmaterials:scissors','Ножницы'},
{'animalmaterials:sword_deamondeath','Меч "Смерть демону!"'},
{'bags:large','Большой рюзак'},
{'bags:medium','Средний рюкзак'},
{'bags:small','Рюкзачок'},
{'barn:barn_empty','Кормушка'},
{'barn:barn_small_empty','Кормушка'},
{'beds:bed_bottom','Кровать'},
{'bees:bees','Дикие пчёлы'},
{'bees:grafting_tool','Графтер'},
{'bees:hive_artificial_inhabited','Улей с пчёлами'},
{'bees:hive_artificial','Улей'},
{'bees:hive','Улей диких пчёл'},
{'bees:honey_bottle','Банка с мёдом'},
{'bees:honey_comb','Мёд'},
{'bees:queen','Королева'},
{'boats:boat','Лодка'},
{'bookex:book','Книга с пером'},
{'buildtest:autocraft','Автоверстак'},
{'buildtest:pipe_cobble_000000_0','Булыжниковая проводящая труба'},
{'buildtest:pipe_diamond_000000_0','Алмазная проводящая труба'},
{'buildtest:pipe_emr_000000_0','Изумрудная проводящая труба'},
{'buildtest:pipe_gate1_000000_0','Управляющая труба 1'},
{'buildtest:pipe_gate2_000000_0','Управляющая труба 2'},
{'buildtest:pipe_gold_000000_0','Золотая проводящая труба'},
{'buildtest:pipe_iron_000000_0','Железная проводящая труба'},
{'buildtest:pipe_meseconoff_000000_0','Месеконовая проводящая труба'},
{'buildtest:pipe_meseconon_000000_0','Месеконовая проводящая труба'},
{'buildtest:pipe_obsidian_000000_0','Обсидиановая проводящая труба'},
{'buildtest:pipe_sandstone_000000_0','Проводящая труба из песчанника'},
{'buildtest:pipe_stone_000000_0','Каменная проводящая труба'},
{'buildtest:pipe_stripe_000000_0','Полосатая проводящая труба'},
{'buildtest:pipe_wood_000000_0','Деревянная проводящая труба'},
{'buildtest:pump_combustion_blue','Двигатель внутреннего сгорания'},
{'buildtest:pump_combustion_green','Двигатель внутреннего сгорания'},
{'buildtest:pump_combustion_red','Двигатель внутреннего сгорания'},
{'buildtest:pump_combustion_yellow','Двигатель внутреннего сгорания'},
{'buildtest:pump_mesecon_blue','Месеконовая помпа'},
{'buildtest:pump_mesecon_green','Месеконовая помпа'},
{'buildtest:pump_mesecon_red','Месеконовая помпа'},
{'buildtest:pump_mesecon_yellow','Месеконовая помпа'},
{'buildtest:pump_stirling_blue','Движок Стирлинга'},
{'buildtest:pump_stirling_green','Движок Стирлинга'},
{'buildtest:pump_stirling_red','Движок Стирлинга'},
{'buildtest:pump_stirling_yellow','Движок Стирлинга'},
{'bushes:basket_blackberry','Корзина с пирогами с черникой'},
{'bushes:basket_blueberry','Корзина с Ежевика Pies'},
{'bushes:basket_empty','Корзина'},
{'bushes:basket_gooseberry','Корзина с Gooseberry Pies'},
{'bushes:basket_mixed_berry','Корзина с из разныхягода Pies'},
{'bushes:basket_raspberry','Корзина с Малина Pies'},
{'bushes:basket_strawberry','Корзина с Клубника Pies'},
{'bushes:blackberry_bush','Черника куст'},
{'bushes:blackberry_pie_cooked','Испечёный Черника пирога'},
{'bushes:blackberry_pie_raw','Сырой Черника пирога'},
{'bushes:blackberry_pie_slice','Кусочек Черника пирога'},
{'bushes:blackberry','Черника'},
{'bushes:blueberry_bush','Ежевика куст'},
{'bushes:blueberry_pie_cooked','Испечёный Ежевика пирога'},
{'bushes:blueberry_pie_raw','Сырой Ежевика пирога'},
{'bushes:blueberry_pie_slice','Кусочек Ежевика пирога'},
{'bushes:blueberry','Ежевика'},
{'bushes:fruitless_bush','Куст без ягод (пока)'},
{'bushes:gooseberry_bush','Gooseberry куст'},
{'bushes:gooseberry_pie_cooked','Испечёный Gooseberry пирога'},
{'bushes:gooseberry_pie_raw','Сырой Gooseberry пирога'},
{'bushes:gooseberry_pie_slice','Кусочек Gooseberry пирога'},
{'bushes:gooseberry','Gooseberry'},
{'bushes:mixed_berry_pie_cooked','Испечёный из разных ягода пирога'},
{'bushes:mixed_berry_pie_raw','Сырой из разных ягода пирога'},
{'bushes:mixed_berry_pie_slice','Кусочек из разных ягода пирога'},
{'bushes:raspberry_bush','Малина куст'},
{'bushes:raspberry_pie_cooked','Испечёный Малина пирога'},
{'bushes:raspberry_pie_raw','Сырой Малина пирога'},
{'bushes:raspberry_pie_slice','Кусочек Малина пирога'},
{'bushes:raspberry','Малина'},
{'bushes:strawberry_bush','Клубника куст'},
{'bushes:strawberry_pie_cooked','Испечёный Клубника пирога'},
{'bushes:strawberry_pie_raw','Сырой Клубника пирога'},
{'bushes:strawberry_pie_slice','Кусочек Клубника пирога'},
{'bushes:strawberry','Клубника'},
{'carts:brakerail','Brake Rail'},
{'carts:cart','Minecart'},
{'carts:powerrail','Powered Rail'},
{'chainsaw:100cc','chainsaw 100cc'},
{'chainsaw:35cc','chainsaw 35cc'},
{'chainsaw:40cc','chainsaw 40cc'},
{'chainsaw:bar','chainsaw bar'},
{'chainsaw:barandchain','chainsaw bar and chain'},
{'chainsaw:chain','chainsaw chain'},
{'chainsaw:powerhead1','chainsaw power head 35cc'},
{'chainsaw:powerhead2','chainsaw power head 40cc'},
{'chainsaw:powerhead3','chainsaw power head 100cc'},
{'chep:cash_xchanger','Cash Xchanger'},
{'chep:misc','Just some trash...'},
{'chests_0gb_us:dropbox','Dropbox'},
{'default:apple_gold','Golden Apple'},
{'default:axe_gold','Gold Axe'},
{'default:axe_iron','Iron Axe'},
{'default:bedrock','Bedrock'},
{'default:charcoal','Charcoal'},
{'default:coal','Coal'},
{'default:fence','Wooden Fence'},
{'default:flint','Flint'},
{'default:gold_nugget','Gold Nugget'},
{'default:gold','Gold Ore'},
{'default:iron_ingot','Iron слиток'},
{'default:iron','Iron Ore'},
{'default:ironblock','Iron Block'},
{'default:pick_gold','Gold кирка'},
{'default:pick_iron','Iron кирка'},
{'default:shears','Shears'},
{'default:shovel_gold','Gold Shovel'},
{'default:shovel_iron','Iron Shovel'},
{'default:snow_brick','Snow Brick'},
{'default:sugar_cane','Sugar Cane'},
{'default:sugar','Sugar'},
{'default:sword_gold','Gold Sword'},
{'default:sword_iron','Iron Sword'},
{'doors:trapdoor','Шлюз'},
{'dye:black','Black dye'},
{'fire:flame_normal','Огонь' },
{'fire:flame_xm_missing','Огонь' },
{'fire:flame_xm_only','Огонь' },
{'fire:flame_xmzm_missing','Огонь' },
{'fire:flame_xmzp_missing','Огонь' },
{'fire:flame_xp_missing','Огонь' },
{'fire:flame_xp_only','Огонь' },
{'fire:flame_xpxm_missing','Огонь' },
{'fire:flame_xpzm_missing','Огонь' },
{'fire:flame_xpzp_missing','Огонь' },
{'fire:flame_zm_missing','Огонь' },
{'fire:flame_zm_only','Огонь' },
{'fire:flame_zp_missing','Огонь' },
{'fire:flame_zp_only','Огонь' },
{'fire:flame_zpzm_missing','Огонь' },
{'firestone:chimney','WIP'},
{'firestone:firestone','Fire node'},
{'firestone:flame_low','Огонь' },
{'firestone:flame','Огонь' },
{'firestone:smoke','smoke'},
{'fishing:bait_worm','Worm'},
{'fishing:bobber_box',''},
{'fishing:fish_raw','Fish'},
{'fishing:fish','Roasted Fish'},
{'fishing:pike_cooked','Roasted Northern Pike'},
{'fishing:pike','Northern Pike'},
{'fishing:pole_deco','Fishing Pole'},
{'fishing:pole','Fishing Pole'},
{'fishing:shark_cooked','Roasted Shark'},
{'fishing:shark','Shark'},
{'fishing:sushi','Sushi (Hoso Maki)'},
{'fishing:trophy_clownfish','Clownfish Trophy'},
{'fishing:trophy_fish_blue_white','Blue white fish Trophy'},
{'fishing:trophy_fish_raw','Fish Trophy'},
{'fishing:trophy_pike','Northern Pike Trophy'},
{'fishing:trophy_shark','Shark Trophy'},
{'gemalde:node_1','Picture #1'},
{'gemalde:node_1','Picture #1'},
{'gemalde:node_2','Picture #2'},
{'gemalde:node_2','Picture #2'},
{'gemalde:node_3','Picture #3'},
{'gemalde:node_3','Picture #3'},
{'gemalde:node_4','Picture #4'},
{'gemalde:node_4','Picture #4'},
{'gemalde:node_5','Picture #5'},
{'gemalde:node_5','Picture #5'},
{'gemalde:node_6','Picture #6'},
{'gemalde:node_6','Picture #6'},
{'gemalde:node_7','Picture #7'},
{'gemalde:node_7','Picture #7'},
{'gemalde:node_8','Picture #8'},
{'gemalde:node_8','Picture #8'},
{'ghosts:ghostly_block','Ghostly Block Generic'},
{'ghosts:ghosttool_2000','Ghost Tool 2000'},
{'ghosts:reincarnator','Reincarnator'},
{'itemframes:frame','Item frame'},
{'itemframes:pedestal','Pedestal'},
{'mesecons_luacontroller:luacontroller1100','Lua контроллер'},
{'mg:dirt_with_dry_grass','Dry Grass'},
{'mg:ignore','MG Ignore'},
{'mg:pineleaves','Pine Leaves'},
{'mg:pinesapling','Pine Sapling'},
{'mg:pinetree','Pine Tree'},
{'mg:pinewood','Pine Planks'},
{'mg:savannaleaves','Savannawood Leaves'},
{'mg:savannasapling','Savannawood Sapling'},
{'mg:savannatree','Savannawood Tree'},
{'mg:savannawood','Savannawood Planks'},
{'mines:dummy','Air (you hacker you!)'},
{'mob_archer:archer','Archer'},
{'mob_guard:guard','Guard'},
{'mob_npc:npc','NPC'},
{'mob_oerkki:oerkki','Oerkki'},
{'mobf:arrow_box',''},
{'mobf:path_marker','Path marker tool'},
{'mobfcooking:cooked_beef','Жареная говядина'},
{'mobfcooking:cooked_chicken','Жареная курица'},
{'mobfcooking:cooked_fish','Жареная рыба'},
{'mobfcooking:cooked_lamb','Жареная баранина'},
{'mobfcooking:cooked_ostrich','Жареная страусятина'},
{'mobfcooking:cooked_pork','Жареная свинина'},
{'mobfcooking:cooked_venison','Жареный вяленый'},
{'mobs:meat_raw','Сырое мясо'},
{'mobs:meat','Мясо'},
{'mobs:rat_cooked','Жареная крыса'},
{'mobs:rat','Крыса'},
{'money:admin_barter_shop','Админский обменник'},
{'money:admin_shop','Магазин от администрации'},
{'money:barter_shop','Обменник'},
{'money:shop','Магазин'},
{'moreores:tin_ingot','Слиток олова'},
{'nanotech:carbon_axe','из карбоволокна Axe'},
{'nanotech:carbon_chest','из карбоволокна Chest'},
{'nanotech:carbon_fibre','Loose Carbon Mesh'},
{'nanotech:carbon_paxel','из карбоволокна Paxel'},
{'nanotech:carbon_pick','из карбоволокна кирка'},
{'nanotech:carbon_plate','Carbon Plate'},
{'nanotech:carbon_rod','Carbon Rod'},
{'nanotech:carbon_shovel','из карбоволокна Shovel'},
{'nanotech:carbon_sword','из карбоволокна Sword'},
{'nanotech:carbonised_wool','Carbonised Wool'},
{'nanotech:drawplate','Drawplate'},
{'nether:brick','Nether Brick'},
{'nether:glowstone','Glowstone'},
{'nether:portal','Nether Portal'},
{'nether:rack','Netherrack'},
{'nether:sand','Nethersand'},
{'oil:ec','Fuel-Energy Converter'},
{'oil:fuel_bucket','Bucket of Fuel'},
{'oil:gfcable_empty','Glass Fibre Cable'},
{'oil:oil_flowing','Oil (flowing)'},
{'oil:oil_source','Oil'},
{'oil:pipe_empty','Pipe'},
{'oil:pipe_wood_fuel',''},
{'oil:pipe_wood','Wood Pipe'},
{'oil:pump_empty','Pump'},
{'oil:pump_oil','Pump'},
{'oil:refinery_empty','Refinery'},
{'oil:siphon_empty','Siphon'},
{'poisonivy:climbing','Poison ivy (climbing plant)'},
{'poisonivy:seedling','Poison ivy (seedling)'},
{'poisonivy:sproutling','Poison ivy (sproutling)'},
{'pyramids:deco_stone1','Sandstone with eye'},
{'pyramids:deco_stone2','Sandstone with men'},
{'pyramids:deco_stone3','Sandstone with sun'},
{'pyramids:spawn_egg','Mummy spawn-egg'},
{'pyramids:spawner_mummy','Mummy spawner'},
{'pyramids:trap_2','trapstone'},
{'pyramids:trap','Cracked sandstone brick'},
{'secret:chestbrick','Secret Chest - Brick'},
{'secret:chestcobble','Secret Chest - Cobblestone'},
{'secret:chestdirt','Secret Chest - Dirt'},
{'secret:chestglass','Secret Chest - Glass'},
{'secret:chestsand','Secret Chest - Sand'},
{'secret:cheststone','Secret Chest - Stone'},
{'secret:chestwood','Secret Chest - Wood'},
{'secret:OneWayMirror','One Way Mirror'},
{'secret:OneWayMirrorbrick','Одностороннее "зеркало" Brick'},
{'secret:OneWayMirrorcobble','Одностороннее "зеркало" Cobble'},
{'secret:OneWayMirrordoorbrick','Одностороннее "зеркало" Door - Brick'},
{'secret:OneWayMirrordoorcobble','Одностороннее "зеркало" Door - Cobble'},
{'secret:OneWayMirrordoorstone','Одностороннее "зеркало" Door - Stone'},
{'secret:OneWayMirrordoorwood','Одностороннее "зеркало" Door - Wood'},
{'secret:OneWayMirrorstone','Одностороннее "зеркало" Stone'},
{'secret:OneWayMirrorwood','Одностороннее "зеркало" Wood'},
{'secret:safedepositbox','Safe Deposit Box'},
{'secret:secret','Secret Essence'},
{'secret:secretdoorbrick','Потайной ход - Brick'},
{'secret:secretdoorcobble','Потайной ход - Cobblestone'},
{'secret:secretdoordirt','Потайной ход - Dirt'},
{'secret:secretdoorglass','Потайной ход - Glass'},
{'secret:secretdoorgrass','Потайной ход - Dirt with Grass'},
{'secret:secretdoorsand','Потайной ход - Sand'},
{'secret:secretdoorstone','Потайной ход - Stone'},
{'secret:secretdoortrunk','Потайной ход - Tree Trunk'},
{'secret:secretdoorwood','Потайной ход - Wood'},
{'shared_autoban:admin_pick_mese','Супер месеконовая кирка'},
{'shared_autoban:admin_pick_steel','Супер железная кирка'},
{'shared_autoban:admin_pick_stone','Супер каменная кирка'},
{'shared_autoban:admin_pick_wood','Супер деревянная кирка'},
{'shared_autoban:rule_em_all_node','Разруливатель пермишенов!'},
{'specialties:axe_gold_feller','Золотой топор (+Автосрубание)'},
{'specialties:axe_gold_superheat','Золотой топор (+Плавка)'},
{'specialties:axe_iron_feller','Железнвй топор (+Автосрубание)'},
{'specialties:axe_iron_superheat','Железный топор (+Плавка)'},
{'specialties:carbon_axe_feller','Топор из карбоволокна (+Автосрубание)'},
{'specialties:carbon_axe_superheat','Топор из карбоволокна (+Плавка)'},
{'specialties:carbon_paxel_feller','Паксель из карбоволокна (+Автосрубание)'},
{'specialties:carbon_paxel_superheat','Паксель из карбоволокна Paxel (+Плавка)'},
{'specialties:carbon_pick_superheat','Кирка из карбоволокна (+Плавка)'},
{'specialties:carbon_shovel_superheat','Лопата из карбоволокна (+Плавка)'},
{'specialties:pick_gold_superheat','Золотая кирка (+Плавка)'},
{'specialties:pick_iron_superheat','Железная кирка (+Плавка)'},
{'specialties:shovel_gold_superheat','Золотая Лопата (+Плавка)'},
{'specialties:shovel_iron_superheat','Железная Лопата (+Плавка)'},
{'streets:asphalt_arrow_alldirs','Asphalt with arrow'},
{'streets:asphalt_arrow_left','Asphalt with arrow'},
{'streets:asphalt_arrow_right','Asphalt with arrow'},
{'streets:asphalt_arrow_straight_left','Asphalt with arrow'},
{'streets:asphalt_arrow_straight_right','Asphalt with arrow'},
{'streets:asphalt_arrow_straight','Asphalt with arrow'},
{'streets:asphalt_dashed_line','Asphalt with dashed line'},
{'streets:asphalt_outer_edge','Asphalt with sideline (edge)'},
{'streets:asphalt_parking','Asphalt with parking label'},
{'streets:asphalt_sideline','Asphalt with sideline'},
{'streets:asphalt_solid_line','Asphalt with solid line'},
{'streets:asphalt','Asphalt'},
{'streets:concrete_wall_flat','Conrete wall'},
{'streets:concrete_wall','Conrete wall'},
{'streets:concrete','Concrete'},
{'streets:constructionfence_bottom','Construction fence'},
{'streets:constructionfence_top','Construction fence'},
{'streets:delineator','Delineator'},
{'streets:emergencyphone','Emergency Phone'},
{'streets:manhole_adv_closed','Advanced manhole'},
{'streets:manhole_adv_open','Advanced manhole'},
{'streets:manhole','Simple manhole'},
{'streets:pole_bottom','Pole'},
{'streets:pole_top','Y u no play minetest without cheating?'},
{'streets:rw_alldirs','Arrow (yellow)'},
{'streets:rw_asphalt_dashed','Dashed line (yellow)'},
{'streets:rw_asphalt_solid','Solid line (yellow)'},
{'streets:rw_cross','Cross (yellow)'},
{'streets:rw_left','Arrow (yellow)'},
{'streets:rw_outer_edge','Outer edge (yellow)'},
{'streets:rw_parking','Parking (yellow)'},
{'streets:rw_right','Arrow (yellow)'},
{'streets:rw_sideline','Sideline (yellow)'},
{'streets:rw_straight_left','Arrow (yellow)'},
{'streets:rw_straight_right','Arrow (yellow)'},
{'streets:rw_straight','Arrow (yellow)'},
{'streets:sign_blank','Emtpy sign'},
{'streets:sign_construction','Warning sign (Construction area)'},
{'streets:sign_lava','Warning sign (lava)'},
{'streets:sign_water','Warning sign (water)'},
{'streets:signworkshop','Sign workshop'},
{'streets:steel_support','Steel support'},
{'streets:streetlamp_basic_bottom','Street lamp'},
{'streets:streetlamp_basic_middle','U cheater U'},
{'streets:streetlamp_basic_top_on','U cheater U'},
{'streets:trafficlight_bottom','Cheater'},
{'streets:trafficlight_controller','Trafficlight'},
{'streets:trafficlight_middle','Cheater!'},
{'streets:trafficlight_top_green','U cheater U'},
{'streets:trafficlight_top_off','U cheater U'},
{'streets:trafficlight_top_red','U cheater U'},
{'streets:trafficlight_top_redyellow','U cheater U'},
{'streets:trafficlight_top_warn','U cheater U'},
{'streets:trafficlight_top_yellow','U cheater U'},
{'trail:wheat_walked','Flattened Wheat'},
{'vines:root','Vine'},
{'vines:rope_block','Rope'},
{'vines:rope_end','Rope'},
{'vines:rope','Rope'},
{'vines:shears','Shears'},
{'vines:side_rotten','Vine'},
{'vines:side','Vine'},
{'vines:vine_rotten','Rotten vine'},
{'vines:vine','Vine'},
{'vines:vines','Vines'},
{'vines:willow_rotten','Vine'},
{'vines:willow','Vine'},
{'voltbuild:advanced_alloy','Advanced alloy'},
{'voltbuild:advanced_circuit','Advanced circuit'},
{'voltbuild:advanced_machine','Advanced machine'},
{'voltbuild:air_cell','Air Cell'},
{'voltbuild:air_compressor','Air Compressor'},
{'voltbuild:alunra_gem','Alunra gem'},
{'voltbuild:alunra_treetap','Alunra Treetap'},
{'voltbuild:batbox','BatBox'},
{'voltbuild:bronze_dust','Bronze dust'},
{'voltbuild:bucket_water_with_ignis','Water with Ignis Bucket'},
{'voltbuild:carbon_fibers','Carbon fibers'},
{'voltbuild:carbon_plate','Carbon plate'},
{'voltbuild:casing','Reactor Heat Casing'},
{'voltbuild:circuit','Electronic circuit'},
{'voltbuild:coal_dust','Coal dust'},
{'voltbuild:combined_carbon_fibers','Combined carbon fibers'},
{'voltbuild:compressor_active','compressor'},
{'voltbuild:compressor','compressor'},
{'voltbuild:copper_cable0_000000','Uninsulated copper cable'},
{'voltbuild:copper_cable1_000000','Insulated copper cable'},
{'voltbuild:copper_dust','Copper dust'},
{'voltbuild:detector_cable_off_000000','Detector cable'},
{'voltbuild:detector_cable_on_000000','Detector cable on, you hacker you'},
{'voltbuild:diamond_drill_discharged','Diamond drill'},
{'voltbuild:diamond_drill','Diamond drill'},
{'voltbuild:electric_furnace_active','Electric furnace'},
{'voltbuild:electric_furnace','Electric furnace'},
{'voltbuild:energy_crystal','Energy crystal'},
{'voltbuild:extractor_active','Extractor'},
{'voltbuild:extractor','Extractor'},
{'voltbuild:fan','Fan'},
{'voltbuild:generator_active','Generator'},
{'voltbuild:generator','Generator'},
{'voltbuild:geothermal_generator','Geothermal Generator'},
{'voltbuild:glass_fiber_cable_000000','Glass fiber cable'},
{'voltbuild:gold_cable0_000000','Uninsulated gold cable'},
{'voltbuild:gold_cable1_000000','Insulated gold cable'},
{'voltbuild:gold_cable2_000000','2xIns. gold cable'},
{'voltbuild:gold_dust','Gold dust'},
{'voltbuild:halt','Halt'},
{'voltbuild:hospital','Hospital'},
{'voltbuild:hv_cable0_000000','Uninsulated HV cable'},
{'voltbuild:hv_cable1_000000','Insulated HV cable'},
{'voltbuild:hv_cable2_000000','2xIns. HV cable'},
{'voltbuild:hv_cable3_000000','3xIns. HV cable'},
{'voltbuild:hv_transformer','HV Transformer'},
{'voltbuild:ice_with_ignis','Ice with Ignis'},
{'voltbuild:ignis_dust','Ignis dust'},
{'voltbuild:ignis_gem','Ignis gem'},
{'voltbuild:iron_dust','Iron dust'},
{'voltbuild:iron_furnace_active','Iron furnace'},
{'voltbuild:iron_furnace','Iron furnace'},
{'voltbuild:lapotron_crystal','Lapotron crystal'},
{'voltbuild:lv_transformer','LV Transformer'},
{'voltbuild:macerator_active','Macerator'},
{'voltbuild:macerator','Macerator'},
{'voltbuild:machine','Machine'},
{'voltbuild:medpack','Medpack'},
{'voltbuild:mfe_unit','MFE Unit'},
{'voltbuild:mfs_unit','MFS Unit'},
{'voltbuild:miner','Miner'},
{'voltbuild:mining_drill_discharged','Mining drill'},
{'voltbuild:mining_drill','Mining drill'},
{'voltbuild:mining_pipe','Mining pipe'},
{'voltbuild:mixed_metal_ingot','Mixed metal ingot'},
{'voltbuild:mobile_solar_panel','Mobile Solar Panel'},
{'voltbuild:mv_transformer','MV Transformer'},
{'voltbuild:nuclear_reaction_chamber','Reaction Chamber'},
{'voltbuild:nuclear_reactor','Nuclear Reactor'},
{'voltbuild:od_scanner','OD Scanner'},
{'voltbuild:ov_scanner','OV Scanner'},
{'voltbuild:overclock','Overclock'},
{'voltbuild:radioactive_shielding','Radioactive Shielding'},
{'voltbuild:re_battery','RE Battery'},
{'voltbuild:reactor_fan','Reactor Fan'},
{'voltbuild:reactor_steam_gen','Reactor Steam Generator'},
{'voltbuild:reactor_wiring','Reactor Wiring'},
{'voltbuild:recycler_active','recycler'},
{'voltbuild:recycler','recycler'},
{'voltbuild:refined_iron_ingot','Refined iron ingot'},
{'voltbuild:rubber_leaves',''},
{'voltbuild:rubber_sapling','Rubber Tree Sapling'},
{'voltbuild:rubber_tree_empty',''},
{'voltbuild:rubber_tree_full','Rubber Tree'},
{'voltbuild:rubber_tree','Rubber Tree'},
{'voltbuild:rubber','Rubber'},
{'voltbuild:sand_with_alunra','Alunra ore'},
{'voltbuild:scrap','Scrap'},
{'voltbuild:scuba_gear','Scuba Gear'},
{'voltbuild:shielded_reactor_wiring','Shielded Reactor Wiring'},
{'voltbuild:silicon_mese_block','Silicon-doped mese block'},
{'voltbuild:silicon_mesecon','Silicon-doped mesecon'},
{'voltbuild:silver_dust','Silver dust'},
{'voltbuild:single_use_battery','Single use battery'},
{'voltbuild:solar_battery','Solar Battery'},
{'voltbuild:solar_panel','Solar panel'},
{'voltbuild:splitter_cable_000000','Splitter cable'},
{'voltbuild:sticky_resin','Sticky resin'},
{'voltbuild:sticky_resin','Sticky resin'},
{'voltbuild:stone_with_uranium','Uranium Ore'},
{'voltbuild:teleport_gloves_discharged','Teleportation Gloves'},
{'voltbuild:teleport_gloves','Teleportation Gloves'},
{'voltbuild:tin_cable0_000000','Uninsulated tin cable'},
{'voltbuild:tin_dust','Tin dust'},
{'voltbuild:treetap','Treetap'},
{'voltbuild:uranium_lump','Uranium lump'},
{'voltbuild:water_flowing_with_ignis','Flowing Water'},
{'voltbuild:water_source_with_ignis','Ignis ore'},
{'voltbuild:watermill','Watermill'},
{'voltbuild:windmill','Windmill'},
{'xpanes:pane_glass','Glass Pane'},
{'xpanes:pane_iron','Iron Fence'},
{'zmobs:egg_lava_flan','Lava flan egg'},
{'zmobs:egg_mese_monster','Mese monster egg'},
{'zmobs:lava_orb','Lava orb'},

}
minetest.after(0, function()

for cou,def in pairs(minetest.registered_nodes) do
    local total2=total
    for tr_name,tr_desc in ipairs (translations) do
        if (def['name']==tr_desc[1]) and (def['description'] ~= tr_desc[2]) then
           def['description'] = tr_desc[2]
           minetest.register_node(':' .. def['name'], def)
           total=total+1
         end
    end
         if total2 == total then
            table.insert(untranslated,{name=def['name'],description = def['description']})
         end
end

for cou,def in pairs(minetest.registered_items) do
    local total2=total
    for tr_name,tr_desc in ipairs (translations) do
        if (def['name']==tr_desc[1]) and (def['description'] ~= tr_desc[2]) then
           def['description'] = tr_desc[2]
           minetest.register_item(':' .. def['name'], def)
           total=total+1
         end
    end
         if total2 == total then
            table.insert(untranslated,{name=def['name'],description = def['description']})
         end
end

for cou,def in pairs(minetest.registered_craftitems) do
    local total2=total
    for tr_name,tr_desc in ipairs (translations) do
        if (def['name']==tr_desc[1]) and (def['description'] ~= tr_desc[2]) then
           def['description'] = tr_desc[2]
           minetest.register_craftitem(':' .. def['name'], def)
           total=total+1
         end
    end
         if total2 == total then
            table.insert(untranslated,{name=def['name'],description = def['description']})
         end
end


for cou,def in pairs(minetest.registered_tools) do
    if (def['name']~=nil) and (def['description']~= nil) then
    local total2=total
    for tr_name,tr_desc in ipairs (translations) do
        if (def['name']==tr_desc[1]) and (def['description'] ~= tr_desc[2]) then
           def['description'] = tr_desc[2]
           minetest.register_tool(':' .. def['name'], def)
           total=total+1
         end
    end
         if total2 == total then
            table.insert(untranslated,{name=def['name'],description = def['description']})
         end
    end
end

minetest.debug('Названия блоков, предметов, инструментов и крафтов переведены! (Всего '.. total ..')')
if #untranslated>0 then
minetest.debug('Однако, есть непереведённые строки. Они сдамплены в untranslated.lua')

--minetest.debug(minetest.serialize(untranslated))
local output = io.open(minetest.get_modpath('localization').."/untranslated.lua", "w")
    if output then
       for _,d in pairs(untranslated) do
       o  = minetest.serialize(d)
       output:write('{\'' .. d['name'] .. '\',\'' .. d['description'] .. '\'},\n')
       end
    end
end

          --  minetest.debug('{\'' .. def['name'] .. '\',\'' .. def['description'] .. '\'},')

end)


