    minetest.register_node("cobweb:cobweb", {
       description = "Cobweb",
       drawtype = "plantlike",
       visual_scale = 1.1,
       tiles = {"cobweb.png"},
       inventory_image = "cobweb.png",
       paramtype = "light",
       sunlight_propagates = true,
       liquid_viscosity = 14,
       liquidtype = "source",
       liquid_alternative_flowing = "cobweb:cobweb",
       liquid_alternative_source = "cobweb:cobweb",
       liquid_renewable = false,
       liquid_range = 0,
       walkable = false,
       groups = {snappy=1,liquid=3},
       drop = "farming:string",
       sounds = default.node_sound_leaves_defaults(),
    })
